apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "couchbase_username" . }}-password
data:
  password: {{ include "couchbase_password" . | b64enc }}